//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public decimal NM_CODICLI { get; set; }
        public string NO_NOMEPES { get; set; }
        public System.DateTime DT_NASCIME { get; set; }
        public System.DateTime DS_CPFCNPJ { get; set; }
    }
}
